#pragma once

// I need this for Intellisense to work right
#if !defined(F_CPU) && !defined(__MK64FX512__) && !defined(USB_EVERYTHING) && !defined(KINETISK)
#define F_CPU 120000000
#define __MK64FX512__
#define USB_EVERYTHING
#define KINETISK
#endif

#include <Arduino.h>

#define delay_us(us) delayMicroseconds(us)

// The toggle registers that PJRC didn't fully implement
#define CORE_PIN0_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN1_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN2_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN3_PORTTOGGLE	GPIOA_PTOR
#define CORE_PIN4_PORTTOGGLE	GPIOA_PTOR
#define CORE_PIN5_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN6_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN7_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN8_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN9_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN10_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN11_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN12_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN13_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN14_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN15_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN16_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN17_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN18_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN19_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN20_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN21_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN22_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN23_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN24_PORTTOGGLE	GPIOE_PTOR
#define CORE_PIN25_PORTTOGGLE	GPIOA_PTOR
#define CORE_PIN26_PORTTOGGLE	GPIOA_PTOR
#define CORE_PIN27_PORTTOGGLE	GPIOA_PTOR
#define CORE_PIN28_PORTTOGGLE	GPIOA_PTOR
#define CORE_PIN29_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN30_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN31_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN32_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN33_PORTTOGGLE	GPIOE_PTOR
#define CORE_PIN34_PORTTOGGLE	GPIOE_PTOR
#define CORE_PIN35_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN36_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN37_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN38_PORTTOGGLE	GPIOC_PTOR
#define CORE_PIN39_PORTTOGGLE	GPIOA_PTOR
#define CORE_PIN40_PORTTOGGLE	GPIOA_PTOR
#define CORE_PIN41_PORTTOGGLE	GPIOA_PTOR
#define CORE_PIN42_PORTTOGGLE	GPIOA_PTOR
#define CORE_PIN43_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN44_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN45_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN46_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN47_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN48_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN49_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN50_PORTTOGGLE	GPIOB_PTOR
#define CORE_PIN51_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN52_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN53_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN54_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN55_PORTTOGGLE	GPIOD_PTOR
#define CORE_PIN56_PORTTOGGLE	GPIOE_PTOR
#define CORE_PIN57_PORTTOGGLE	GPIOE_PTOR
#define CORE_PIN58_PORTTOGGLE	GPIOE_PTOR
#define CORE_PIN59_PORTTOGGLE	GPIOE_PTOR
#define CORE_PIN60_PORTTOGGLE	GPIOE_PTOR
#define CORE_PIN61_PORTTOGGLE	GPIOE_PTOR
#define CORE_PIN62_PORTTOGGLE	GPIOE_PTOR
#define CORE_PIN63_PORTTOGGLE	GPIOE_PTOR
